const myObj = data;
let body = document.querySelector('.body');
for (var i = 0; i < Object.keys(myObj.type).length; i++) {
     var btnWrapper = document.createElement("button");
     btnWrapper.setAttribute("class", "wrapper");
     btnWrapper.setAttribute("id", i);
     btnWrapper.setAttribute("onClick", "reply_click(this.id)");
     var divAffichage = document.createElement("div");
     divAffichage.setAttribute("class", "affichage");
     var img = document.createElement("img");
     img.setAttribute("src", myObj.type[i].image);
     var pNom = document.createElement("p");
     pNom.setAttribute("class", "nom");
     pNom.innerHTML = myObj.type[i].name;
     var pNote = document.createElement("p");
     pNote.innerHTML = myObj.type[i].note;
     pNote.setAttribute("class", "note");
     body.appendChild(btnWrapper);
     btnWrapper.appendChild(divAffichage);
     divAffichage.appendChild(img);
     divAffichage.appendChild(pNom);
     divAffichage.appendChild(pNote);
}

function reply_click(clicked_id){
    id = clicked_id;
    let main = document.querySelector('.reset');
    main.innerHTML = '';
    var h1 = document.createElement("h1");
        h1.setAttribute("id","title_detail");
        h1.innerHTML = myObj.type[clicked_id].name;
    var lea = document.createElement("div");
        lea.setAttribute("class","lea");
    var mainText = document.createElement("div");
        mainText.setAttribute("class","main_text");
    var mainTT = document.createElement("h2");
        mainTT.setAttribute("id","main_text_title");
        mainTT.innerHTML = 'Découvrir';
    var adresse = document.createElement("p");
        adresse.innerHTML = 'adresse: '+myObj.type[clicked_id].adresse;
    var tel = document.createElement("p");
        tel.innerHTML = 'tel: '+myObj.type[clicked_id].numero;
    var text = document.createElement("p");
        text.innerHTML = myObj.type[clicked_id].resumer;
    var cont_L = document.createElement("div");
        cont_L.setAttribute("class","container_left");
    var critTitle = document.createElement("h1");
        critTitle.setAttribute("id","criteria_title");
        critTitle.innerHTML = 'Les Critères <span id="green">GREEN</span>';
    var green = document.createElement("span");
        green.setAttribute("id","green");
        green.innerHTML = 'GREEN';
    var notation = document.createElement("div");
        notation.setAttribute("class","notation");
    var criteria = document.createElement("div");
        criteria.setAttribute("class","criteria");
    var rating = document.createElement("div");
        rating.setAttribute("class","rating");
    var jumbo = document.createElement("div");
        jumbo.setAttribute("class","jumbotron");
    var table = document.createElement("table");
    var thead = document.createElement("thead");
    var tr1 = document.createElement("tr");
    var tbody = document.createElement("tbody");
    var tr2 = document.createElement("tr");
    var br = document.createElement("br");
    var br2 = document.createElement("br");
    main.appendChild(h1);
    main.appendChild(lea);
        lea.appendChild(mainText);
            mainText.appendChild(mainTT);
            mainText.appendChild(br);
            mainText.appendChild(adresse);
            mainText.appendChild(tel);
            mainText.appendChild(br2);
            mainText.appendChild(text);
        lea.appendChild(cont_L);
            cont_L.appendChild(critTitle);
            cont_L.appendChild(notation);
                notation.appendChild(criteria);
                notation.appendChild(rating);
    main.appendChild(jumbo);
        jumbo.appendChild(table);
            table.appendChild(thead);
                thead.appendChild(tr1);
            table.appendChild(tbody);
                tbody.appendChild(tr2);
                    for (var i=0 ; i< Object.keys(myObj.type[clicked_id].critere).length ;i+=1)
                    {
                        var th = document.createElement("th");
                        th.innerHTML = myObj.type[clicked_id].critere[i].name;
                        tr1.appendChild(th);
                        var td = document.createElement("td");
                        tr2.appendChild(td);
                        var img = document.createElement("img");
                            img.setAttribute("src",myObj.type[clicked_id].critere[i].img);
                            td.appendChild(img);
                        var crit =document.createElement("div");
                            crit.setAttribute("class","criterion");
                            criteria.appendChild(crit);
                        var img2 = document.createElement("img");
                            img2.setAttribute("class","icon");
                            img2.setAttribute("src",myObj.type[clicked_id].critere[i].img);
                            crit.appendChild(img2);
                        var r = document.createElement("div");
                            r.setAttribute("class",myObj.type[clicked_id].critere[i].note);
                            rating.appendChild(r);
                    }
}

